### ISSUE TITLE
Monitorización Básica con Prometheus

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#127]
# Ejercicio Introductorio: Monitorización Básica con Prometheus

Configura **Prometheus** para recolectar métricas de un contenedor **nginx** usando Docker, realiza consultas para obtener información sobre el uso de CPU y memoria, y analiza los resultados. Luego, detén y elimina los contenedores utilizados.

**Tareas:**  
- Instala y configura Prometheus con un archivo `prometheus.yml`.  
- Levanta un contenedor `nginx` con Docker.  
- Accede a Prometheus en `http://localhost:9090` y realiza consultas como `nginx_http_requests_total`, `container_cpu_usage_seconds_total` y `container_memory_usage_bytes`.  
- Analiza las métricas obtenidas y detén los contenedores al finalizar.

**Comment by SokiSotos** [comment]
Jose Sotos Pérez

**Comment by SokiSotos** [comment]
### **Instrucciones**

1. Crear app/index.html

```
<!DOCTYPE html>
<html>
<head>
    <title>Servidor Nginx</title>
</head>
<body>
    <h1>Hola desde Nginx</h1>
</body>
</html>
```

2. Crear default.conf (configuración de Nginx)

```
server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /stub_status {
        stub_status;
        allow all;
    }
}
```

3. Crear prometheus.yml

```
global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
```

4. Crear docker-compose.yml

```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      - nginx
    ports:
      - "9113:9113"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
```

5. Arrancar los servicios

`docker-compose up -d`

![Image](https://github.com/user-attachments/assets/f39043e9-69fe-4f37-90e2-413b4df4d7aa)

6. Acceder a los servicios

· Nginx → http://localhost:8080

![Image](https://github.com/user-attachments/assets/8c607c03-a9a6-428c-a2b6-6c5ed368cb27)

· Prometheus → http://localhost:9090

![Image](https://github.com/user-attachments/assets/ac99404f-bcf4-44c7-ab55-54249e6bc0ac)

· Exportador → http://localhost:9113/metrics

![Image](https://github.com/user-attachments/assets/eaaada52-c69b-433b-8a62-6af9f130b078)

7. Consultas en Prometheus

Abro http://localhost:9090

Las consultas `container_cpu_usage_seconds_total` y `container_memory_usage_bytes` no dan muestras por que nginx-prometheus-exporter, solo expone métricas internas de Nginx (peticiones, conexiones, errores, etc.) y prometheus, recolecta lo que le digas, pero no sabe nada del sistema por sí solo.

Así que me he tomado la molestia de poner otras consultas de nginx que si expone desde prometheus.

`nginx_up` → Verifica si el exporter accede a Nginx

![Image](https://github.com/user-attachments/assets/6df559ac-ee12-4479-94c9-8ebff05613d2)

`nginx_http_requests_total` → Número de peticiones HTTP

![Image](https://github.com/user-attachments/assets/d29e6035-6c22-4767-9075-65ba78015f55)

`nginx_connections_active` → Conexiones activas

![Image](https://github.com/user-attachments/assets/44f1ebdd-7839-4939-a0b5-75a6bcc21f8b)

`nginx_connections_reading, writing, waiting` → Estados de conexión

![Image](https://github.com/user-attachments/assets/7dfc6242-7680-4668-b4d6-b58067825596)

8. Análisis de métricas obtenidas

nginx_up

    Valor: 1 → Todo correcto, Prometheus puede acceder al exportador.

    Valor: 0 → Error de conexión entre el exportador y Nginx.

nginx_http_requests_total

    Cuenta cuántas peticiones HTTP ha gestionado Nginx desde que se inició.

nginx_connections_active

    Muestra cuántas conexiones están activas en este momento.

nginx_connections_reading, writing, waiting

    Estas métricas indican el estado de las conexiones:

        Reading: leyendo la solicitud del cliente.

        Writing: enviando la respuesta al cliente.

        Waiting: conexión keep-alive esperando nueva solicitud.


9. Detener y eliminar contenedores

`docker-compose down`

![Image](https://github.com/user-attachments/assets/fe5f238c-4aa6-466c-b238-ea2d6ff082f5)
