### ISSUE TITLE
Configurar un contenedor para servir una aplicación PHP+Nginx

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#222]

**Comment by davmacdi99** [comment]
David Macias

**Comment by davmacdi99** [comment]
**CONFIGURAR UN CONTENEDOR PARA SERVIR UNA APLICACIÓN PHP+NGINX**

1- Crear un archivo docker-compose.yml dentro de una carpeta.

> nano docker-compose.yml

Escribimos dentro el siguiente contenido:

```
version: "3.8"

# Servidor nginx
services:
  web:
    image: nginx:latest
    # Puerto 8080 
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  # Configuración de php-fpm
  php-fpm:
    image: php:8-fpm
    volumes:
      - ./src:/var/www/html

```

2- Dentro de la misma carpeta, creamos un nuevo archivo con el nombre default.conf con la siguiente configuración

>nano default.conf

```
server {
    listen 80;
    server_name phpfpm.local;
    root /var/www/html;

    index index.php index.html;  

    error_log /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

  
    location / {
        try_files $uri $uri/ /index.php?$query_string;  
    }

  
    location ~ \.php$ {
        try_files $uri =404;  
        fastcgi_pass php-fpm:9000;  
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}

```

![Image](https://github.com/user-attachments/assets/c3d66993-1e71-49ce-a0a6-44f8c2b64d90)

3- Creamos e iniciamos el contenedor

>docker-compose -up -d

![Image](https://github.com/user-attachments/assets/3703e7f2-b81c-4699-bc39-53f8653c44e2)

4- Compruebo que estén iniciados correctamente:

>docker ps

![Image](https://github.com/user-attachments/assets/53c89782-eab1-49e1-9456-0b55f1b5d8e1)

5- Dentro de la carpeta src, crearé un archivo index.php.

>nano index.php

![Image](https://github.com/user-attachments/assets/159b7611-d686-4d62-8d8c-ed4fa903faa2)

Con el contenido:

```
<?php
  echo phpinfo();
```

![Image](https://github.com/user-attachments/assets/0f1a740b-0b87-445f-ae79-9ccfa7d4367d)

6- Desde el navegador, accedemos a:

`http://localhost:8080/`

![Image](https://github.com/user-attachments/assets/0afd2e12-da67-4b4e-b8da-011cc7e0f867)

**¡YA ESTÁ LISTO SERVIDOR NGINX CORRIENDO JUNTO PHP USANDO DOCKER_COMPOSE!**
