### ISSUE TITLE
Monitorización Básica con Prometheus

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#230]
# Ejercicio Introductorio: Monitorización Básica con Prometheus

Configura **Prometheus** para recolectar métricas de un contenedor **nginx** usando Docker, realiza consultas para obtener información sobre el uso de CPU y memoria, y analiza los resultados. Luego, detén y elimina los contenedores utilizados.

**Tareas:**  
- Instala y configura Prometheus con un archivo `prometheus.yml`.  
- Levanta un contenedor `nginx` con Docker.  
- Accede a Prometheus en `http://localhost:9090` y realiza consultas como `nginx_http_requests_total`, `container_cpu_usage_seconds_total` y `container_memory_usage_bytes`.  
- Analiza las métricas obtenidas y detén los contenedores al finalizar.

**Comment by davmacdi99** [comment]
David Macias

**Comment by davmacdi99** [comment]
**MONITORIZACIÓN BÁSICA CON PROMETHEUS**

He creado una carpeta llamada Prometheus para este proyecto, donde lo primero que haré será el archivo prometheus.yml, dentro de esta carpeta.

>nano prometheus.yml

Con esta configuración:
                                                                                                   
```
global:
  scrape_interval: 15s

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-prometheus-exporter:9113']
```

![Image](https://github.com/user-attachments/assets/2be1d687-7bec-4352-a69d-2e6c428fea87)

Después realizaré el docker-compose:

>nano docker-compose.yml

```
   version: '3.8'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-prometheus-exporter
    ports:
      - "9113:9113"
```
                                                                                   
![Image](https://github.com/user-attachments/assets/0dd2df88-b592-4f11-a6c8-1ecc46d192dc)

Levantamos el contenedor:

>docker-compose up -d

![Image](https://github.com/user-attachments/assets/49dac8c5-8b1b-45c7-92e4-77159e281657)

Navegamos en nuestro navegador a:

>http://localhost:9090

![Image](https://github.com/user-attachments/assets/201dd42a-90d2-44bc-9a91-c12e625dc3a5)

Los servicios están UP:

![Image](https://github.com/user-attachments/assets/ddca4e54-5c15-43a9-9d31-48857287de22)
