### ISSUE TITLE
Optimizar Configuraciones

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#238]
En este ejercicio realizarás una auditoría de configuraciones existentes para mejorar la eficiencia de contenedores y redes Docker.

---

## **Instrucciones**

1. Revisa los archivos `docker-compose.yml` y configuraciones de conatenedores previos.
2. Aplica las siguientes optimizaciones:
   - **Reducción de tamaños de imágenes:** Cambia imágenes grandes por versiones optimizadas (por ejemplo, usa `nginx:alpine` en lugar de `nginx:latest`).
   - **Persistencia de datos:** Asegúrate de que todos los datos necesarios están almacenados en volúmenes.
   - **Límites de recursos:** Configura límites de CPU y memoria para los servicios en Docker Compose:
     ```yaml
     resources:
       limits:
         memory: 256m
         cpus: "0.5"
     ```

3. Valida las optimizaciones iniciando los servicios:
   ```bash
   docker-compose up -d
   ```

4. Documenta los cambios realizados y las mejoras esperadas.

---

**Comment by davmacdi99** [comment]
David Macias

**Comment by davmacdi99** [comment]
**OPTIMIZAR CONFIGURACIONES**

1- Revisa los archivos docker-compose.yml y configuraciones de contenedores previos.

Usaré el docker-compose.yml del proyecto PHP+NGINX:

![Image](https://github.com/user-attachments/assets/bf0f9d7b-9923-4c11-b70d-362b2cd469ca)

Accederé al archivo:

>nano docker-compose.yml

Y aplicaremos los cambios para las optimizaciones:

- Reducción de tamaños de imágenes: Cambia imágenes grandes por versiones optimizadas (por ejemplo, usa nginx:alpine en lugar de nginx:latest).
- Persistencia de datos: Asegúrate de que todos los datos necesarios están almacenados en volúmenes.
- Límites de recursos: Configura límites de CPU y memoria para los servicios en Docker Compose:

```
resources:
  limits:
    memory: 256m
    cpus: "0.5"
```

El archivo quedaría así:

```
version: "3.8"


services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    resources:
      limits:
        memory: 256m
        cpus: "0.5"


  php-fpm:
    image: php:8-fpm-alpine
    volumes:
      - ./src:/var/www/html
    resources:
      limits:
        memory: 256m
        cpus: "0.5"

```

![Image](https://github.com/user-attachments/assets/cab51f86-c013-4e71-a6e4-ee79d8f3d606)

Validamos las optimizaciones iniciando los servicios:

>docker-compose up -d

![Image](https://github.com/user-attachments/assets/9494ed3a-24bc-4c4b-8b85-fd924866ef7d)

Con esto esperamos una mejora en la eficencia de los contenedores Docker, así como el uso de recursos. Donde hemos usado imágenes más ligeras que también ayudan a reducir los tiempos de inicio de los contenedores y uso de espacio en disco.
