### ISSUE TITLE
Docker Compose Avanzado

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#278]
Docker Compose Avanzado

En este ejercicio aprenderás a configurar un archivo `docker-compose.yml` que gestione múltiples servicios, redes y volúmenes.

---

## **Instrucciones**

1. Crea un archivo `docker-compose.yml` con la siguiente estructura básica:
   ```yaml
   version: '3.8'

   services:
     web:
       image: nginx:latest
       networks:
         - frontend
       ports:
         - "8080:80"

     app:
       image: php:7.4-fpm
       networks:
         - backend
       volumes:
         - ./app:/var/www/html

     db:
       image: mysql:5.7
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: testdb
       networks:
         - backend
       volumes:
         - db_data:/var/lib/mysql

   networks:
     frontend:
     backend:

   volumes:
     db_data:
   ```

2. Inicia los servicios:
   ```bash
   docker-compose up -d
   ```

3. Valida que todos los servicios están activos:
   ```bash
   docker-compose ps
   ```

4. Detén y elimina los servicios y volúmenes al finalizar:
   ```bash
   docker-compose down -v
   ```

**Comment by Alvaro-nepo** [comment]
**Docker Compose Avanzado**

Como en los anteriores ejercicios ya hemos utilizado el archivo docker-compose.yml, hemos creado otra carpeta en donde realizaremos este ejercicio para evitar problemas con configuraciones previas.

En esta caso en vez de hacerlo por comandos he creado una carpeta nueva en mi directorio personal, y click derecho abrir en la terminal, una vez ahí siempre hago un sudo su para minimizar errores  :D 
Una vez hecho eso creamos el archivo:

` nano docker-compose.yml`

Y escribimos:

```
version:` '3.8'

services:
  web:
    image: nginx:latest
    networks:
      - frontend
    ports:
      - "8080:80"

  app:
    image: php:7.4-fpm
    networks:
      - backend
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  db_data:
```
 
Control x y guardamos.

**Iniciar los servicios con Docker Compose**

Ejecutamos el siguiente comando para iniciar los servicios en segundo plano:

`docker-compose up -d`

![Image](https://github.com/user-attachments/assets/f561fbba-235e-4345-aa8f-70952cfb065f)


![Image](https://github.com/user-attachments/assets/df52ec09-19e1-4a41-9da3-6260a913b81a)

Esperamos a que los contenedores se descarguen e inicien correctamente.


**Verificar los servicios en ejecución**

Para comprobar que los contenedores están corriendo correctamente, usamos el siguiente comando:

`docker-compose ps`

Esto mostrará una lista de los contenedores en ejecución con su estado.

![Image](https://github.com/user-attachments/assets/b431f490-9e5f-4016-bc93-02556fe1cf4e)



 **Detener y eliminar los servicios**

Cuando hayamos terminado con el ejercicio, podemos detener y eliminar todos los contenedores, redes y volúmenes con el siguiente comando:

docker-compose down -v

Esto limpiará completamente nuestro entorno de Docker.


![Image](https://github.com/user-attachments/assets/96e5c6eb-3c8f-4574-a1a5-22f35a1eca09)


`


`
