### ISSUE TITLE
Configurar un contenedor para servir una aplicación PHP+Nginx

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#296]

**Comment by pasmussenv** [comment]
Paula Asmussen

**Comment by pasmussenv** [comment]
### Paso 1: Creo la estructura de carpetas.

```
cd ~/Documents
mkdir php_nginx_app
cd php_nginx_app
mkdir app
mkdir nginx
```

![Image](https://github.com/user-attachments/assets/27ff8092-708d-4070-9422-aabdc5b9dc12)

**- app :** contendrá el archivo index.php
**- nginx:** contendrá el archivo default.conf con la configuración de Nginx.

###  Paso 2: Creo el archivo index.php.
Dentro de la carpeta app, creo el archivo índex.php para pruebas de funcionamiento .

`nano index.php`

Y pego el código
```
php
CopiarEditar
<?php
phpinfo();
?>
```
![Image](https://github.com/user-attachments/assets/b38ba812-eb5b-404b-ac3e-d7c5606a8f83)

Este script de PHP muestra toda la información de configuración del servidor.
 
### Paso 3: Creo la configuración de Nginx
Entro en la carpeta nginx y creo el archivo de configuración del servidor:

```
cd ../nginx
nano default.conf
```

Una vez dentro del archivo, creo el script de bloque de configuración para un virtual host de Nginx, que le indicará cómo comportarse al recibir peticiones web. 

```
server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
}

```
Explicación del script:

```
server {
    listen 80;
```
Es el puerto típico del tráfico HTTP.

   ` server_name localhost;`

Define el nombre del servidor

 ```
   root /var/www/html;
    index index.php index.html;
```
Le dice dónde están los archivos de la web y cuál es la página de inicio por defecto.
/var/www/html es donde se monta mi carpeta app con el index.php.

  ```
  location / {
        try_files $uri $uri/ =404;
    }
```
Le dice que Intente servir el archivo solicitado y si no existe, que devuelva un error 404.

  ```
  location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
    }
```

le dice a Nginx cómo pasar los archivos .php al contenedor php (donde está PHP-FPM) para que los ejecute.

![Image](https://github.com/user-attachments/assets/5b170676-4c67-4ee3-9c36-bf62dbb0d457)

### Paso 4: Creo el archivo docker-compose.yml
Vuelvo a la raíz de php_nginx_app y creo el docker-compose.yml:

`cd ~/Documents/php_nginx_app`

`nano docker-compose.yml`

```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./app:/var/www/html


```

![Image](https://github.com/user-attachments/assets/fdcde7c6-eb91-41ab-a4a8-c3ce660ee515)

Explicación (chuleta): 

```
version: '3.8'
# Define la versión del archivo docker-compose.

services:
  nginx:
    image: nginx:latest
    # Usa la imagen oficial de Nginx para servir contenido web.

    ports:
      - "8080:80"
      # Expone el puerto 80 del contenedor donde escucha nginx al puerto 8080 (local host).

    volumes:
      - ./app:/var/www/html
      # Monta la carpeta local 'app/' dentro del contenedor en /var/www/html.

      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Reemplaza el archivo de configuración por defecto de Nginx por uno personalizado.

    depends_on:
      - php
      # Nginx espera a que el contenedor php esté listo antes de iniciarse.

  php:
    image: php:7.4-fpm
    # Usa la imagen oficial de PHP en modo FPM (FastCGI) para interpretar scripts PHP.

    volumes:
      - ./app:/var/www/html
      # Monta también la carpeta 'app/' para que PHP pueda ejecutar los scripts desde allí.

# Resultado:
# Nginx y PHP trabajan juntos.
# - Nginx sirve el contenido.
# - PHP ejecuta el código PHP usando FPM.
# Todo se muestra accediendo a http://localhost:8080


```
### Paso 5: Levanto los servicios

`docker-compose up -d --build`

**up:** levanta los servicios del docker-compose.yml.
**-d:** lo hace en modo detached (en segundo plano)
**--build:** fuerza a Docker a reconstruir las imágenes, por si hubo cambios en los archivos de configuración.

![Image](https://github.com/user-attachments/assets/8d7839cd-3ccf-478a-b73e-1157515a10e9)

### Paso 6: Verificación
Abro el navegador y entro a:

`http://localhost:8080`

Para comprobar que todo va bien.

![Image](https://github.com/user-attachments/assets/6fa9261a-3351-4c62-af6e-7e48f0f937f0)
