### ISSUE TITLE
Configurar un contenedor para servir una aplicación PHP+Nginx

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#297]

**Comment by Alvaro-nepo** [comment]
**Crear la Carpeta del Proyecto**
Primero, creamos una carpeta para organizar los archivos del proyecto:

```
mkdir php-nginx-app
cd php-nginx-app
```
**Crear el Archivo docker-compose.yml**
Vamos a definir los servicios en un archivo docker-compose.yml que usará Nginx como servidor web y PHP-FPM para ejecutar código PHP.
`nano docker-compose.yml`

Y ponemos lo siguiente:
```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: php-nginx
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network

  php:
    image: php:8.2-fpm
    container_name: php-fpm
    volumes:
      - ./html:/var/www/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

```
php: Contenedor con PHP-FPM para procesar el código PHP.

volumes: Se monta la carpeta ./html para que ambos contenedores tengan acceso a los archivos.

depends_on: Asegura que Nginx se inicie solo después de que PHP esté corriendo.

networks: Define una red interna para que ambos contenedores se comuniquen.

![Image](https://github.com/user-attachments/assets/88e324c1-5553-40ab-a37f-8a2648249b47)

**Configurar Nginx para Servir Archivos PHP**
Ahora creamos la configuración de Nginx para que pueda interpretar PHP.

`nano nginx.conf`

Y añadimos la configuracion base
```
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
```
server {}: Configura el servidor en el puerto 80.

root /var/www/html;: Establece la carpeta donde estarán los archivos.

index index.php index.html;: Prioriza el uso de index.php.

location ~ \.php$ {}: Configura Nginx para que use PHP-FPM en el puerto 9000


**Crear la Carpeta y un Archivo PHP de Prueba**

```
mkdir html
nano html/index.php
```
y añadimos el este código de prueba

```
<?php
phpinfo();
?>

```


![Image](https://github.com/user-attachments/assets/ef272453-9a7b-4da5-a3f4-8925f28d4487)

**Construir y Levantar los Contenedores**

`docker-compose up -d`

![Image](https://github.com/user-attachments/assets/45d9cb1e-5359-48f8-a402-aa36511ec91b)

Y vamos  a http://localhost:8080, para comprobar que todo esta perfecto :D

![Image](https://github.com/user-attachments/assets/2a2d7a41-62a4-4e09-bf66-8b79df825cbe)
