### ISSUE TITLE
Monitorización Básica con Prometheus

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#303]
# Ejercicio Introductorio: Monitorización Básica con Prometheus

Configura **Prometheus** para recolectar métricas de un contenedor **nginx** usando Docker, realiza consultas para obtener información sobre el uso de CPU y memoria, y analiza los resultados. Luego, detén y elimina los contenedores utilizados.

**Tareas:**  
- Instala y configura Prometheus con un archivo `prometheus.yml`.  
- Levanta un contenedor `nginx` con Docker.  
- Accede a Prometheus en `http://localhost:9090` y realiza consultas como `nginx_http_requests_total`, `container_cpu_usage_seconds_total` y `container_memory_usage_bytes`.  
- Analiza las métricas obtenidas y detén los contenedores al finalizar.

**Comment by Alvaro-nepo** [comment]
alvaronepo

**Comment by Alvaro-nepo** [comment]
Para explicar un poco, he configurado Prometheus para recolectar métricas de un contenedor de Nginx usando Docker. Además, he implementado cAdvisor para obtener métricas de uso de CPU y memoria de los contenedores y he resuelto varios errores en el proceso. A continuación, lo explico todo, se puede hacer tmb sin el cAdvisor pero creo que es la manera mas cómoda debido a que nos da hasta mas comandos para utilizar :D.

No hace falta explicarlo pero lo digo, antes de empezar con todo esto creamos una carpeta nueva en nuestro directorio personal llamado por ejemplo Prometheus, y la abrimos en la terminal para minimizar los posibles errores que puedan ocurrir.

**Paso 1: Preparar el entorno con Docker y Docker Compose**
Para comenzar, primero necesitamos preparar un entorno con Docker y Docker Compose. Utilicé un archivo docker-compose.yml para facilitar la configuración de todos los contenedores (Prometheus, Nginx, nginx-exporter y cAdvisor).

Archivo docker-compose.yml:
Este es el archivo que utilicé para definir todos los contenedores. Aquí se especifican los servicios de Prometheus, Nginx, nginx-exporter y cAdvisor.
```
version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command: 
      - -nginx.scrape-uri=http://nginx/stub_status
    ports:
      - "9113:9113"
    depends_on:
      - nginx
    networks:
      - monitoring

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge

```
Como podeis ver aqui ya incluyo todo, nginx, el exporter y el cAdvisor.
Para explicarlo mejor os dejo esto:

Prometheus: Recoge las métricas de Nginx y cAdvisor. Se le asigna el puerto 9090 para acceder a su interfaz web.

Nginx: Contenedor de Nginx. Está configurado para exponer métricas en /stub_status.

nginx-exporter: Exportador de métricas de Nginx que expone las métricas de Nginx a Prometheus en el puerto 9113.

cAdvisor: Contenedor que recolecta las métricas de uso de CPU y memoria de los contenedores Docker.

**Paso 2: Configuración de Prometheus**

Ahora, para que Prometheus pueda recolectar las métricas, necesitamos configurarlo adecuadamente. Para ello, creamos un archivo llamado prometheus.yml donde se definen los trabajos (jobs) para recolectar las métricas de Nginx y cAdvisor.

Archivo prometheus.yml:

```
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']



```
Incluimos también el advisor

![Image](https://github.com/user-attachments/assets/41e05e1e-9fd4-43cb-bed3-775052326d66)

**Paso 3: Configuración de Nginx para Exponer Métricas**
Para que nginx-exporter pueda recoger las métricas de Nginx, necesitamos habilitar el endpoint /stub_status en la configuración de Nginx. Si no hacemos esto probablemente en el status dentro del prometheus ponga DOWN.
El archivo si no lo tenéis creado se puede crear sin problema:

Archivo nginx.conf:

**server {
    listen 80;

    location /stub_status {
        stub_status on;
        access_log off;
        allow 127.0.0.1;
        deny all;
    }
}**
**Paso 4: Levantar los Contenedores con Docker Compose**

docker-compose up -d

Y los verificamos 

docker ps

![Image](https://github.com/user-attachments/assets/7bc406d7-100e-470d-938c-ad1251ea3901)


**Paso 5: Consultar las Métricas en Prometheus**

Accedí a la interfaz web de Prometheus en http://localhost:9090/ para realizar algunas consultas y ver las métricas.

`nginx_http_requests_total`

Podemos ver que funcionan 

![Image](https://github.com/user-attachments/assets/75c7243f-feb5-4eb5-810f-c3944d16d2ff)

Y también las consultas relacionadas con la cpu:

`container_cpu_usage_seconds_total`

![Image](https://github.com/user-attachments/assets/79bd6e08-4acb-40e7-a7af-0e6bfcd76391)

**Paso Final: Detener y Eliminar los Contenedores**

Una vez completado todo este realizado y comrpobamos que todo funciona ,detuve y eliminé los contenedores con:


`docker-compose down`

Esto apaga todos los contenedores y elimina la red creada.
