### ISSUE TITLE
Monitorización Básica con Prometheus

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#305]
# Ejercicio Introductorio: Monitorización Básica con Prometheus

Configura **Prometheus** para recolectar métricas de un contenedor **nginx** usando Docker, realiza consultas para obtener información sobre el uso de CPU y memoria, y analiza los resultados. Luego, detén y elimina los contenedores utilizados.

**Tareas:**  
- Instala y configura Prometheus con un archivo `prometheus.yml`.  
- Levanta un contenedor `nginx` con Docker.  
- Accede a Prometheus en `http://localhost:9090` y realiza consultas como `nginx_http_requests_total`, `container_cpu_usage_seconds_total` y `container_memory_usage_bytes`.  
- Analiza las métricas obtenidas y detén los contenedores al finalizar.

**Comment by Hector-Sanchez19** [comment]
Héctor

**Comment by Hector-Sanchez19** [comment]
Lo primero que haremos para crear y configurar prometheus será crear su respectiva carpeta con sus archivos.

`mkdir prometheus && cd prometheus`

`nano prometheus.yml`

Dentro de **prometheus.yml** escribiremos lo siguiente:

```
global:
  scrape_interval: 5s  # Intervalo de recolección de métricas

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']

  - job_name: 'docker'
    static_configs:
      - targets: ['cadvisor:8080']
```

Ahora crearemos el archivo docker-compose.yml.

`nano docker-compose.yml`

Dentro de aquí agregaremos lo siguiente:

```
version: '3.8'

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - monitoring

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8081:80"
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: nginx-exporter
    command:
      - "-nginx.scrape-uri=http://nginx:80/stub_status"
    ports:
      - "9113:9113"
    networks:
      - monitoring
    depends_on:
      - nginx

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - "8083:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    networks:
      - monitoring

networks:
  monitoring:
```
Lo siguiente que vamos a hacer sera realizar un `docker-compose up -d`, en mi caso tuve 2 errores por el tema de los puertos que estaban ocupados.

**ERRORES**

Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint nginx (02e5adc8d348291802de3af3e92ab264c18b9961c2de3076c43906fce75e8733): Bind for 0.0.0.0:8080 failed: port is already allocated

Error response from daemon: failed to set up container networking: driver failed programming external connectivity on endpoint cadvisor (e70b812364fb11f58e3c040f396977c38753e5c6e58ad3e776740e76b608f7f6): Bind for 0.0.0.0:8080 failed: port is already allocated

**SOLUCIÓN**

Arreglar este problema es bastante sencillo lo único que tendremos que hacer será ir al archivo **docker-compose.yml** y cambiarle los puertos a nginx y cadvisor que son los dos que nos están dando problemas en este caso. Una vez cambiados realizaremos nuevamente `docker-compose up -d`

![Image](https://github.com/user-attachments/assets/c77b9055-a44c-4120-a297-15ca1869382f)

Si lo hemos hecho todo correcto nos dejará acceder a **http://localhost:9090**.

![Image](https://github.com/user-attachments/assets/ad4b6b88-cd29-4760-b845-f4e7028d3e9c)

En la barra de búsqueda realizaremos unas cuantas búsquedas como ejemplos. (nginx_http_requests_total, container_cpu_usage_seconds_total y container_memory_usage_bytes.)

**nginx_http_requests_total**, este muestra el total de solicitudes recibidas por NGINX.

![Image](https://github.com/user-attachments/assets/ebbccb98-a2fe-4f0a-9c22-9981b521a4de)

**container_cpu_usage_seconds_total**, este otro nos indica cuántos segundos de CPU han usado los contenedores.

![Image](https://github.com/user-attachments/assets/7ac1c4a1-f830-45a4-8516-8fc10b5e8b50)

**container_memory_usage_bytes**, y por último, este nos muestra el uso de memoria de los contenedores.

![Image](https://github.com/user-attachments/assets/96db66cc-7f99-4e3c-9e3e-5425688da8c9)

Una vez realizadas las consultas y hayamos acabado procederemos a detener los contenedores con `docker-compose down`.

![Image](https://github.com/user-attachments/assets/df16c3d6-ff88-44cb-80dd-e520a85cf54e)

¡Con esto hemos acabado!
