### ISSUE TITLE
Optimizar Configuraciones

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#312]
En este ejercicio realizarás una auditoría de configuraciones existentes para mejorar la eficiencia de contenedores y redes Docker.

---

## **Instrucciones**

1. Revisa los archivos `docker-compose.yml` y configuraciones de conatenedores previos.
2. Aplica las siguientes optimizaciones:
   - **Reducción de tamaños de imágenes:** Cambia imágenes grandes por versiones optimizadas (por ejemplo, usa `nginx:alpine` en lugar de `nginx:latest`).
   - **Persistencia de datos:** Asegúrate de que todos los datos necesarios están almacenados en volúmenes.
   - **Límites de recursos:** Configura límites de CPU y memoria para los servicios en Docker Compose:
     ```yaml
     resources:
       limits:
         memory: 256m
         cpus: "0.5"
     ```

3. Valida las optimizaciones iniciando los servicios:
   ```bash
   docker-compose up -d
   ```

4. Documenta los cambios realizados y las mejoras esperadas.

---

**Comment by pasmussenv** [comment]
Paula Asmussen

**Comment by pasmussenv** [comment]
### Optimizar configuraciones en la tarea: Configurar un contenedor para servir una aplicación PHP+Nginx.  

**1. Entro en la carpeta del proyecto y reviso el archivo docker-compose.yml.**

`cd ~/Documents/php_nginx_app`

`nano docker-compose.yml`

```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./app:/var/www/html

```

![Image](https://github.com/user-attachments/assets/f88f2a25-e939-4c2c-89b1-15fc96434066)

**2. Auditoría y propuesta de mejora.**

**a) Reducción del tamaño de las imágenes:** Las imágenes utilizadas originalmente (nginx:latest y php:7.4-fpm) son versiones completas que ocupan bastante espacio.

**- Propuesta de mejora:** Reemplazarlas por versiones más ligeras como nginx:alpine y php:7.4-fpm-alpine. 

**b) Límites de recursos:** No hay limites de recursos definidos.   

**- Propuesta de mejora:** añadir límites de memoria (250 MB) y CPU (0,5), para mejorar la eficiencia.

```
deploy:
  resources:
    limits:
      memory: 256m
      cpus: "0.5"
```

**c) Persistencia de datos:** Los volúmenes ya están correctamente definidos. No se requieren cambios.

_Nota: El **deploy** sirve para poner límites de memoria y CPU a los contenedores. Se usa para decirle a Docker cuánto puede usar cada servicio.
Aunque lo pongamos, solo se aplica en Docker Swarm, no en docker-compose up. Pero es una buena práctica y ayuda a documentar la configuración._


![Image](https://github.com/user-attachments/assets/64a525e7-8af8-4fa9-a4ce-f24923420bf9)


**3. Prueba de cambios realizados:** 

Reinicio los contenedores y levanto el proyecto con los cambios realizados.

`docker-compose down`

![Image](https://github.com/user-attachments/assets/ba7a7ae2-ea16-450d-ad51-538ae39bbc68)

`docker-compose up -d --build`

![Image](https://github.com/user-attachments/assets/d556cdf1-6ebd-43e3-a8de-7b9e8c3f1aae)

_Nota: - -build fuerza la reconstrucción con las nuevas imágenes y aplica los nuevos límites de recursos._

**4. Por último compruebo que todo esté funcionando correctamente:**

`docker ps`

![Image](https://github.com/user-attachments/assets/326d8ba0-3a45-431d-a543-3c1ac296286b)

![Image](https://github.com/user-attachments/assets/203df3c9-c290-40eb-b61f-590ffc80dedf)
