### ISSUE TITLE
Optimizar Configuraciones

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#316]
En este ejercicio realizarás una auditoría de configuraciones existentes para mejorar la eficiencia de contenedores y redes Docker.

---

## **Instrucciones**

1. Revisa los archivos `docker-compose.yml` y configuraciones de conatenedores previos.
2. Aplica las siguientes optimizaciones:
   - **Reducción de tamaños de imágenes:** Cambia imágenes grandes por versiones optimizadas (por ejemplo, usa `nginx:alpine` en lugar de `nginx:latest`).
   - **Persistencia de datos:** Asegúrate de que todos los datos necesarios están almacenados en volúmenes.
   - **Límites de recursos:** Configura límites de CPU y memoria para los servicios en Docker Compose:
     ```yaml
     resources:
       limits:
         memory: 256m
         cpus: "0.5"
     ```

3. Valida las optimizaciones iniciando los servicios:
   ```bash
   docker-compose up -d
   ```

4. Documenta los cambios realizados y las mejoras esperadas.

---

**Comment by Alvaro-nepo** [comment]
alvaronepo

**Comment by Alvaro-nepo** [comment]
**Optimización de Docker Compose**
Vamos a utilizar una configuración con Apache (httpd) y Nginx, para aplicar mejoras de optimización en el archivo docker-compose.yml, ya teniamos este proyecto existente debido a las prácticas anteriores, es en el que utilizabamos el puerto 80 y el 81 :D 
 Cambios realizados:
✅ Se cambió httpd:latest por httpd:alpine (versión más ligera).
✅ Se aseguraron volúmenes persistentes para los datos de la web.
✅ Se establecieron límites de CPU y memoria para mejorar el rendimiento.

Encontramos el archivo docker compose y lo editamos

![Image](https://github.com/user-attachments/assets/52740fa7-1385-4cb1-95d5-b3be908daff4)

`nano docker-compose.yml`

Podemos ver como esta el código con el "latest", y ahora procedemos a cambiarlo quedaría tal que así:

```
version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

  app:
    image: httpd:alpine  # Cambiado a versión más ligera
    ports:
      - "8081:80"
    volumes:
      - ./app:/usr/local/apache2/htdocs/
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

volumes:
  html:
  app:

```
 Modificaciones aplicadas:

-httpd:latest → httpd:alpine

-Añadimos límites de CPU/memoria.

-Definimos volúmenes correctamente.

Una vez hecho esto guardamos el archivo y lo cerramos.

Detenemos los contenedores antiguos (podríamos haberlo hecho antes tmb)

**docker-compose down**

Y levantamos los optimizados:

**docker-compose up -d**


![Image](https://github.com/user-attachments/assets/af324f30-c151-4fe7-9dc2-63f6e19bd79c)


Ahora vamos a los puertos correspondientes, y  como podemos comprobar funciona perfectamente después de haber hecho las optimizaciones:





 **Resumen de Mejoras**
-Ahora los contenedores usan imágenes más ligeras, reduciendo consumo de espacio y carga.

-Los volúmenes garantizan persistencia de datos, evitando pérdida de información.

-Se han agregado límites de CPU y memoria para evitar que consuman más recursos de los necesarios.

![Image](https://github.com/user-attachments/assets/a0fee802-d999-4e22-bbc8-0f23cfca953d)
![Image](https://github.com/user-attachments/assets/f32245e2-f271-4065-beb3-42562ddc72be)
