### ISSUE TITLE
Optimizar Configuraciones

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#339]
En este ejercicio realizarás una auditoría de configuraciones existentes para mejorar la eficiencia de contenedores y redes Docker.

---

## **Instrucciones**

1. Revisa los archivos `docker-compose.yml` y configuraciones de conatenedores previos.
2. Aplica las siguientes optimizaciones:
   - **Reducción de tamaños de imágenes:** Cambia imágenes grandes por versiones optimizadas (por ejemplo, usa `nginx:alpine` en lugar de `nginx:latest`).
   - **Persistencia de datos:** Asegúrate de que todos los datos necesarios están almacenados en volúmenes.
   - **Límites de recursos:** Configura límites de CPU y memoria para los servicios en Docker Compose:
     ```yaml
     resources:
       limits:
         memory: 256m
         cpus: "0.5"
     ```

3. Valida las optimizaciones iniciando los servicios:
   ```bash
   docker-compose up -d
   ```

4. Documenta los cambios realizados y las mejoras esperadas.

---

**Comment by SokiSotos** [comment]
Jose Sotos Pérez

**Comment by SokiSotos** [comment]
### **Instrucciones**

He utilizado el `docker-compose.yml` de la practica de Prometheus y lo he modificado de la siguiente forma:

### **docker-compose.yml original.**

```
version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      - nginx
    ports:
      - "9113:9113"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
```

### **docker-compose.yml optimizado**

```
version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - "--nginx.scrape-uri=http://nginx:80/stub_status"
    depends_on:
      - nginx
    ports:
      - "9113:9113"
    deploy:
      resources:
        limits:
          memory: 128m
          cpus: "0.2"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      resources:
        limits:
          memory: 256m
          cpus: "0.5"

```

Al usar `docker stats` podemos ver la mejora, respecto al `docker-compose.yml` original.

### **docker-compose.yml optimizado**
![Image](https://github.com/user-attachments/assets/c7319b40-55e0-4626-96c6-1133037c85d1)

### **docker-compose.yml original.**
![Image](https://github.com/user-attachments/assets/52b2202e-151a-4030-98e5-e3ff06dae932)

Estas mejoras hacen que la infraestructura sea:

    · Más ligera.
    · Más controlada en recursos.
    · Más mantenible y lista para adaptarse a entornos productivos o integrarse con otras herramientas.
