### ISSUE TITLE
Mejorar la seguridad de la red Docker

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#369]
### **Objetivo:**  
Revisar la configuración de redes en Docker y aplicar buenas prácticas de seguridad para mejorar el aislamiento y control de acceso entre contenedores.  

### **Tareas a realizar:**  
1. **Listar y analizar las redes Docker existentes.**  
2. **Inspeccionar la configuración de cada red para detectar posibles vulnerabilidades.**  
3. **Aplicar mejoras en la segmentación de redes, asegurando que los contenedores solo se comuniquen cuando sea necesario.**  
4. **Configurar reglas de firewall en el host para limitar accesos no autorizados.**  
5. **Definir redes específicas en un archivo `docker-compose.yml` para organizar mejor la arquitectura.**  
6. **Verificar la efectividad de la configuración mediante pruebas de conectividad entre contenedores y escaneos de puertos desde redes externas.**  
7. **Documentar los resultados en una archivo `network-security.txt` ubicado en `docker/exercise/security/`.**  

### **Pista:**  
Para probar la seguridad de la red, intenta conectarte desde un contenedor a otro y desde el host hacia los servicios expuestos. Usa herramientas como `nmap` o `curl` para verificar qué puertos están abiertos y qué servicios están accesibles.

**Comment by SokiSotos** [comment]
Jose Sotos Pérez

**Comment by SokiSotos** [comment]
### **Instrucciones**
 
1. Listar y analizar las redes Docker existentes
`docker network ls`

![Image](https://github.com/user-attachments/assets/8a5d3e90-e48f-4c55-90a3-ccac7e595abb)

2. Inspeccionar cada red para detectar vulnerabilidades
`docker network inspect bridge`

![Image](https://github.com/user-attachments/assets/9f6ab573-0ac1-4bfd-b494-a0153e36936a)

3. Aplicar segmentación de red

Creamos dos redes:

frontend: para servicios públicos
backend: interna, sin acceso a internet

```
version: '3.8'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    networks:
      - frontend

  app:
    image: php:8.1-apache
    container_name: app
    networks:
      - frontend
      - backend

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backend

```
4. Configurar reglas de firewall en el host

```
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw enable
```

Esto bloquea todo excepto lo permitido.

![Image](https://github.com/user-attachments/assets/99ef2998-c51c-4355-a54e-2ed1057edab9)

6. Verificar efectividad mediante pruebas

Usamos netshoot para probar conectividad:

`docker run -it --rm --network=seguridad_backend nicolaka/netshoot`

Desde ahí, probar:

ping db - debe responder
ping app - debe responder
ping nginx - debe fallar (no está en backend)
curl http://google.com - debe fallar (sin salida a Internet)

![Image](https://github.com/user-attachments/assets/92008057-e7d8-47bc-b0d7-ed0e94f85a67)

7. Documentación de los resultados

![Image](https://github.com/user-attachments/assets/66693d8b-3777-47b5-93df-33a52807720c)
