### ISSUE TITLE
Docker Compose Avanzado

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#94]
Docker Compose Avanzado

En este ejercicio aprenderás a configurar un archivo `docker-compose.yml` que gestione múltiples servicios, redes y volúmenes.

---

## **Instrucciones**

1. Crea un archivo `docker-compose.yml` con la siguiente estructura básica:
   ```yaml
   version: '3.8'

   services:
     web:
       image: nginx:latest
       networks:
         - frontend
       ports:
         - "8080:80"

     app:
       image: php:7.4-fpm
       networks:
         - backend
       volumes:
         - ./app:/var/www/html

     db:
       image: mysql:5.7
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: testdb
       networks:
         - backend
       volumes:
         - db_data:/var/lib/mysql

   networks:
     frontend:
     backend:

   volumes:
     db_data:
   ```

2. Inicia los servicios:
   ```bash
   docker-compose up -d
   ```

3. Valida que todos los servicios están activos:
   ```bash
   docker-compose ps
   ```

4. Detén y elimina los servicios y volúmenes al finalizar:
   ```bash
   docker-compose down -v
   ```
