### ISSUE TITLE
Docker Compose Avanzado

### ISSUE THREAD

**Issue by Erik-FM02** [Erik-FM02/Onboarding-devops-#96]
Docker Compose Avanzado

En este ejercicio aprenderás a configurar un archivo `docker-compose.yml` que gestione múltiples servicios, redes y volúmenes.

---

## **Instrucciones**

1. Crea un archivo `docker-compose.yml` con la siguiente estructura básica:
   ```yaml
   version: '3.8'

   services:
     web:
       image: nginx:latest
       networks:
         - frontend
       ports:
         - "8080:80"

     app:
       image: php:7.4-fpm
       networks:
         - backend
       volumes:
         - ./app:/var/www/html

     db:
       image: mysql:5.7
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: testdb
       networks:
         - backend
       volumes:
         - db_data:/var/lib/mysql

   networks:
     frontend:
     backend:

   volumes:
     db_data:
   ```

2. Inicia los servicios:
   ```bash
   docker-compose up -d
   ```

3. Valida que todos los servicios están activos:
   ```bash
   docker-compose ps
   ```

4. Detén y elimina los servicios y volúmenes al finalizar:
   ```bash
   docker-compose down -v
   ```

**Comment by SokiSotos** [comment]
Jose Sotos Pérez

**Comment by SokiSotos** [comment]
**### Instrucciones**

1. Crea un archivo docker-compose.yml con la siguiente estructura:

```
version: '3.8'

services:
  web:
    image: nginx:latest
    networks:
      - frontend
    ports:
      - "8080:80"

  app:
    image: php:7.4-fpm
    networks:
      - backend
    volumes:
      - ./app:/var/www/html

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql

networks:
  frontend:
  backend:

volumes:
  db_data:
```

![Image](https://github.com/user-attachments/assets/e6e8ec48-9454-4086-a714-8b15de3e0ba9)

2. Inicia los servicios:

`docker-compose up -d`

![Image](https://github.com/user-attachments/assets/ba6fd97c-fb5c-4eae-ba0d-1a13103b2da3)

3. Valida que todos los servicios están activos:

`docker-compose ps`

![Image](https://github.com/user-attachments/assets/36683fc6-e25b-4179-86f0-558fbe6791c0)

4. Detén y elimina los servicios y volúmenes al finalizar:

`docker-compose down -v`

![Image](https://github.com/user-attachments/assets/1a29663f-f618-46e9-90a8-4fc1236de761)
